services:
  - type: web
    name: rag-chatpdf
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: USE_GROQ
        value: "true"
